apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  labels:
    osp/interface: enp6s0
  name: enp6s0-crc
spec:
  desiredState:
    interfaces:
    - description: Configuring Bridge
      name: osptestbr
      mtu: 1500
      type: linux-bridge
      state: up
      bridge:
        options:
          stp:
            enabled: false
      ipv4:
        address:
        - ip: 192.168.222.10
          prefix-length: 24
        enabled: true
        dhcp: false
      ipv6:
        enabled: false
